### ISSUE TITLE
Change Implementation Syntax For Component

### ISSUE THREAD

**Issue by Kiricon** [AlaskaAirlines/auro-table#3]
## Is your feature request related to a problem? Please describe.
This "issue" in question is the implementation of the data binding in the component. 
Having data you want rendered passed in as a json object in to the attribute is a bad practice and takes away agency form users to modify specific elements in the component as needed. A forced re-render of the entire table on attribute change for a single column of data is generally a bad practice.

You can see this practice actually listed as something you shouldn't do in google's web components best practices guide [here](https://developers.google.com/web/fundamentals/web-components/best-practices#attributes-properties). This format breaks 4 of the best practices outlined in the "Attributes and properties" section of the guide. 

Issue in question: 
```HTML
columnHeaders='["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]'
  componentData='[
  {"": "Dance class", "Monday": "5:00pm","Wednesday": "5:00pm" },
  {"": "Night classes", "Thursday": "7:00pm","Friday": "7:00pm" },
  {"": "Team meeting", "Wednesday": "10:00am" },
  {"": "Morning workout", "Monday": "8:00am", "Tuesday": "8:00am", "Wednesday": "8:00am", "Thursday": "8:00am", "Friday": "8:00am" }
]'
```

This format is extremely non-standard for normal HTML spec and component libraries in general. This format also will cause issues with libraries / frameworks that would usually play nicely with html components (React specifically comes to mind when doing this type of data binding, and the account team specifically has had issues with this type of format in the past). 

## Describe the solution you'd like
I'd love to see a more HTML first solution for data binding. In normal HTML and other popular component libraries you see data laid out in a more readable html way, with use of multiple html tags to accomplish data binding.
Example of normal HTML data binding: 
```HTML
<label for="cars">Choose a car:</label>

<select name="cars" id="cars" multiple>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="opel">Opel</option>
  <option value="audi">Audi</option>
</select>
```

Take note of the use of multiple elements to accomplish the goal of rendering a single "select" option, and how each element only binds a single value to itself. The html is easy to read, modify and clear about what exactly is going to be rendered.

Some similar example from Google's material design components:
```HTML
<mwc-list id="basic">
      <mwc-list-item selected>Item 0</mwc-list-item>
      <mwc-list-item>Item 1</mwc-list-item>
      <mwc-list-item>Item 2</mwc-list-item>
      <mwc-list-item>Item 3</mwc-list-item>
</mwc-list>
```
```HTML
<mwc-tab-bar>
      <mwc-tab label="one"></mwc-tab>
      <mwc-tab label="two"></mwc-tab>
      <mwc-tab label="three"></mwc-tab>
</mwc-tab-bar
```

[This documentation](https://developers.google.com/web/fundamentals/web-components/examples/howto-tabs) by google on how to implement tabs is a good example of how you should binding data to custom elements.

**Comment by Kiricon** [comment]
Also here is an example of a component that originally followed the json object format, that was causing issues for the account team that was later re-written to support the web components best practices.

https://github.com/AlaskaAirlines/ods-inputoptions

**Comment by Kiricon** [comment]
Also meant to include this example from the popular "Ionic" component library
```HTML
<ion-menu side="start" menu-id="first" content-id="main">
    <ion-header>
      <ion-toolbar color="primary">
        <ion-title>Start Menu</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content>
      <ion-list>
        <ion-item>Menu Item</ion-item>
        <ion-item>Menu Item</ion-item>
        <ion-item>Menu Item</ion-item>
        <ion-item>Menu Item</ion-item>
        <ion-item>Menu Item</ion-item>
      </ion-list>
    </ion-content>
  </ion-menu>
```

**Comment by blackfalcon** [comment]
There are a couple of takeaways from this feedback that I want to address. 

We 100% agree with the idea that web components should follow traditional HTML where it makes sense. What you are proposing is really re-inventing the structure of the native HTML table syntax and I don't see the value of creating a web component at that low feature level. The examples you provided make much more sense as there are other attributes involved and complex interactions. 

The scope of this table is for the simple use of displaying static data. Not complex data that allows for heavy interaction. In the research we did, we found that potential users of this component already have all the data in a JSON format, and in order to produce the table have to repeat the logic we put into this component. 

What does need to be documented is the WCSS partner to this component where the same table can be created with consistent CSS if the developer chooses to build their own table for more complex interactive data or simply want more control over the table itself. 

When you are saying, "This format breaks 4 of the best practices ...", correct me if I am wrong, but the statements there is what is being addressed with [Lit Element here](https://lit-element.polymer-project.org/guide/properties#attributes). 

In regards to the updates to ods-inputOptions, there is some news. Due to constraints with accessibility and having to basically re-invent all the interactions of radio buttons in native HTML, for that component specifically we went back to using a blob of JSON to define the buttons. That being said, we know that this is less than optimal. But we also discovered that many of the other implemented solutions by other teams simply do not meet the accessibility spec. There are the same issues across all the browsers.

Again, less than optimal, but helpful in some cases. To counter this, there will be a CSS counterpart of the radio buttons and checkboxes if the developer so chooses to go that route. 

Further documentation will be released that illustrated the best use case for this component and alternatives for less than optimal use cases.
